# This file is a general .xdc for the Basys3 rev B board
# To use it in a project:
# - uncomment the lines corresponding to used pins
# - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
    set_property IOSTANDARD LVCMOS33 [get_ports clk]

# create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

# Switches
set_property PACKAGE_PIN V17 [get_ports {sw_in[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw_in[0]}]
set_property PACKAGE_PIN V16 [get_ports {sw_in[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw_in[1]}]
set_property PACKAGE_PIN W16 [get_ports {sw_in[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw_in[2]}]
set_property PACKAGE_PIN W17 [get_ports {sw_in[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw_in[3]}]
# set_property PACKAGE_PIN W15 [get_ports {sw[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
# set_property PACKAGE_PIN V15 [get_ports {sw[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
# set_property PACKAGE_PIN W14 [get_ports {sw[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
# set_property PACKAGE_PIN W13 [get_ports {sw[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
# set_property PACKAGE_PIN V2 [get_ports {sw[8]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
# set_property PACKAGE_PIN T3 [get_ports {sw[9]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
# set_property PACKAGE_PIN T2 [get_ports {sw[10]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
# set_property PACKAGE_PIN R3 [get_ports {sw[11]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
# set_property PACKAGE_PIN W2 [get_ports {sw[12]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
# set_property PACKAGE_PIN U1 [get_ports {sw[13]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
#set_property PACKAGE_PIN T1 [get_ports {capture_notclassify}]
#   set_property IOSTANDARD LVCMOS33 [get_ports {capture_notclassify}]

#set_property PACKAGE_PIN R2 [get_ports {reset}]
 #   set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
set_property PACKAGE_PIN R2 [get_ports {reset_LCD}]
    set_property IOSTANDARD LVCMOS33 [get_ports {reset_LCD}]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {leds[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property PACKAGE_PIN E19 [get_ports {leds[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property PACKAGE_PIN U19 [get_ports {leds[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property PACKAGE_PIN V19 [get_ports {leds[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property PACKAGE_PIN W18 [get_ports {leds[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property PACKAGE_PIN U15 [get_ports {leds[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
set_property PACKAGE_PIN U14 [get_ports {leds[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property PACKAGE_PIN V14 [get_ports {leds[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]
set_property PACKAGE_PIN V13 [get_ports {leds[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[8]}]
set_property PACKAGE_PIN V3 [get_ports {leds[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[9]}]
set_property PACKAGE_PIN W3 [get_ports {leds[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[10]}]
set_property PACKAGE_PIN U3 [get_ports {leds[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[11]}]
set_property PACKAGE_PIN P3 [get_ports {leds[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[12]}]
    
#set_property PACKAGE_PIN N3 [get_ports {leds[13]}]
 #   set_property IOSTANDARD LVCMOS33 [get_ports {leds[13]}]
#set_property PACKAGE_PIN P1 [get_ports {leds[14]}]
 #   set_property IOSTANDARD LVCMOS33 [get_ports {leds[14]}]
#set_property PACKAGE_PIN L1 [get_ports {leds[15]}]
 #   set_property IOSTANDARD LVCMOS33 [get_ports {leds[15]}]

# 7 segment display
set_property PACKAGE_PIN W7 [get_ports {cathodes[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[0]}]
set_property PACKAGE_PIN W6 [get_ports {cathodes[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[1]}]
set_property PACKAGE_PIN U8 [get_ports {cathodes[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[2]}]
set_property PACKAGE_PIN V8 [get_ports {cathodes[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[3]}]
set_property PACKAGE_PIN U5 [get_ports {cathodes[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[4]}]
set_property PACKAGE_PIN V5 [get_ports {cathodes[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[5]}]
set_property PACKAGE_PIN U7 [get_ports {cathodes[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cathodes[6]}]

# set_property PACKAGE_PIN V7 [get_ports dp]
# set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN U2 [get_ports {anodes[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {anodes[0]}]
set_property PACKAGE_PIN U4 [get_ports {anodes[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {anodes[1]}]
set_property PACKAGE_PIN V4 [get_ports {anodes[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {anodes[2]}]
set_property PACKAGE_PIN W4 [get_ports {anodes[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {anodes[3]}]

# Buttons
#set_property PACKAGE_PIN U18 [get_ports thumb_btn]
 #   set_property IOSTANDARD LVCMOS33 [get_ports thumb_btn]
set_property PACKAGE_PIN U18 [get_ports reset]
    set_property IOSTANDARD LVCMOS33 [get_ports reset]    
    
    
set_property PACKAGE_PIN T18 [get_ports upper_btn]
    set_property IOSTANDARD LVCMOS33 [get_ports upper_btn]
    
set_property PACKAGE_PIN W19 [get_ports cursor_left_btn]
    set_property IOSTANDARD LVCMOS33 [get_ports cursor_left_btn]
set_property PACKAGE_PIN T17 [get_ports cursor_right_btn]
    set_property IOSTANDARD LVCMOS33 [get_ports cursor_right_btn]

set_property PACKAGE_PIN U17 [get_ports lower_btn]
    set_property IOSTANDARD LVCMOS33 [get_ports lower_btn]

# Pmod Header JXADC
set_property PACKAGE_PIN J3 [get_ports {vauxp6}]
    set_property IOSTANDARD LVCMOS33 [get_ports {vauxp6}]
set_property PACKAGE_PIN L3 [get_ports {vauxp14}]
    set_property IOSTANDARD LVCMOS33 [get_ports {vauxp14}]
set_property PACKAGE_PIN M2 [get_ports {vauxp7}]
    set_property IOSTANDARD LVCMOS33 [get_ports {vauxp7}]
set_property PACKAGE_PIN N2 [get_ports {vauxp15}]
    set_property IOSTANDARD LVCMOS33 [get_ports {vauxp15}]
set_property PACKAGE_PIN K3 [get_ports {vauxn6}]
    set_property IOSTANDARD LVCMOS33 [get_ports {vauxn6}]
set_property PACKAGE_PIN M3 [get_ports {vauxn14}]
    set_property IOSTANDARD LVCMOS33 [get_ports {vauxn14}]
set_property PACKAGE_PIN M1 [get_ports {vauxn7}]
    set_property IOSTANDARD LVCMOS33 [get_ports {vauxn7}]
set_property PACKAGE_PIN N1 [get_ports {vauxn15}]
    set_property IOSTANDARD LVCMOS33 [get_ports {vauxn15}]
    
# Pmod Header JA
set_property PACKAGE_PIN J1 [get_ports {thumb_btn}]
    set_property IOSTANDARD LVCMOS33 [get_ports {thumb_btn}]

    
# Pmod Header JB
set_property PACKAGE_PIN A14 [get_ports {LCD_RS}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LCD_RS}]
set_property PACKAGE_PIN A16 [get_ports {LCD_RW}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LCD_RW}]
set_property PACKAGE_PIN B15 [get_ports {LCD_EN}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LCD_EN}]

# Pmod Header JC
set_property PACKAGE_PIN K17 [get_ports {LCD_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[0]}]
set_property PACKAGE_PIN M18 [get_ports {LCD_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[1]}]
set_property PACKAGE_PIN N17 [get_ports {LCD_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[2]}]
set_property PACKAGE_PIN P18 [get_ports {LCD_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[3]}]
set_property PACKAGE_PIN L17 [get_ports {LCD_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[4]}]
set_property PACKAGE_PIN M19 [get_ports {LCD_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[5]}]
set_property PACKAGE_PIN P17 [get_ports {LCD_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[6]}]
set_property PACKAGE_PIN R18 [get_ports {LCD_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[7]}]
